# Generated by Django 4.1.2 on 2022-12-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Funcao', models.CharField(choices=[('Aula', 'Aula'), ('Admin', 'Admin')], max_length=50)),
                ('Comprimento', models.CharField(blank=True, max_length=10, null=True)),
                ('Altura', models.CharField(blank=True, max_length=10, null=True)),
                ('Profundidade', models.CharField(blank=True, max_length=10, null=True)),
                ('Disponibilidade', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('Lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapa.local')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('Numero', models.IntegerField(unique=True)),
                ('Curso', models.CharField(max_length=50)),
                ('Turno', models.CharField(choices=[('Integral', 'Integral'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=8)),
                ('Salas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.sala')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProduto', models.CharField(db_column='Nome do Produto', max_length=50)),
                ('NomePessoa', models.CharField(max_length=50)),
                ('Situação', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Análise', 'Análise'), ('Reprovado', 'Reprovado')], default='Análise', max_length=9)),
                ('Valor', models.FloatField(db_column='R$')),
                ('Lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapa.local')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Salas', smart_selects.db_fields.GroupedForeignKey(group_field='Lugar', on_delete=django.db.models.deletion.CASCADE, to='Login.sala')),
            ],
        ),
        migrations.CreateModel(
            name='AdminEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('Nome', models.CharField(max_length=50, unique=True)),
                ('Funcao', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Salas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.sala')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
