# Generated by Django 4.1.2 on 2022-12-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, null=True, verbose_name='Primeiro Nome')),
                ('UltimoNome', models.CharField(max_length=100, null=True, verbose_name='Ultimo Nome')),
                ('TipoUsuario', models.CharField(choices=[('Docente', 'Docente'), ('Discente', 'Discente'), ('Visitante', 'Visitante')], max_length=9, null=True, verbose_name='Tipo de Usuário')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
